add echo of error and exit if failed

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -50,8 +50,6 @@ jobs:
               --parameters 'commands=["aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin ${{ steps.login-aws-ecr.outputs.registry }}"]' \
               --query "Command.CommandId" --output text)
 
-            echo "$command_id"
-
             aws ssm wait command-executed \
               --command-id $command_id \
               --instance-id i-0f270cb598a238d0b
@@ -64,6 +62,8 @@ jobs:
               echo "Command executed successfully"
             else
               echo "Command failed"
+              echo "Error: $status"
+              exit 1
             fi
 
 
